### ISSUE TITLE
Seems to now require explicit -R option?

### ISSUE THREAD

**Issue by patricksurry** [Ebonsignori/plant-uml-water#3]
If I try to invoke without `-R` I get a confusing error message.  Adding `-R .` works but took me a minute.  Perhaps result of last PR?

```water-uml live diagram.puml
/usr/local/lib/node_modules/water-plant-uml/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.isAbsolute (node:path:1157:5)
    at Object.handler (/usr/local/lib/node_modules/water-plant-uml/water-uml.js:24:20)
    at Object.runCommand (/usr/local/lib/node_modules/water-plant-uml/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/water-plant-uml/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/usr/local/lib/node_modules/water-plant-uml/node_modules/yargs/build/index.cjs:2651:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/water-plant-uml/water-uml.js:137:5)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.0.1
```

**Comment by Ebonsignori** [comment]
Good catch, thank you so much for reporting this :)

Fixed it and added a [changelog](https://github.com/Ebonsignori/water-plant-uml/blob/main/CHANGELOG.md) in latest release
